const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const page=new JSDOM(fs.readFileSync('static/index.html','utf8'),{url:'https://projektzeit.test',runScripts:'outside-only',pretendToBeVisual:true}),w=page.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
let clock;w.setInterval=fn=>{clock=fn;return 1;};w.clearInterval=()=>{};
const main=w.document.querySelector('main');for(const name of ['projects','statistics','workshop-status']){if(!w.document.querySelector('#view-'+name)){const v=w.document.createElement('section');v.id='view-'+name;v.className='view';main.append(v);}}
const calls=[];const policy={approval_paid:true,approval_unpaid:true,hourly_paid:false,minimum_minutes:30,correction_mode:'request',self_approval:false};
w.fixturePost=async(path,body)=>{calls.push({path,body});if(path.endsWith('/context'))return {policy,permissions:['staff.manage','staff.policy','bookkeeping.view','payroll.manage','staff.view'],people:[{id:1,username:'Test',first_name:'Vorname',last_name:'Nachname'},{id:2,username:'Kollege'}],kinds:[{code:'vacation',name:'Urlaub'}],subdivisions:['SH']};if(path.endsWith('/report'))return {own:!body.user_id||Number(body.user_id)===1,user_id:Number(body.user_id)||1,from:'2026-09-14',to:'2026-09-20',week_number:38,movements:[],days:[{day:'2026-09-07',target_seconds:28800,worked_seconds:25200,delta_seconds:-3600,labels:[],state:'closed'}],work:[{id:1,started_at:'2026-09-07T07:00:00Z',ended_at:'2026-09-07T14:00:00Z'}],projects:[{project_name:'Kassenupdate',started_at:'2026-09-07T08:00:00Z',ended_at:'2026-09-07T10:00:00Z'}],requests:[],posted_seconds:-3600,movement_seconds:0,account:{balance_seconds:7200,configured:true},vacation:{available:20e6,after_pending:20e6,configured:true,entitlement:20e6,taken:0,approved:0,pending:0}};if(path.endsWith('/calendar'))return {events:[]};return {ok:true};};
w.eval(`var state={user:{id:1}};var post=window.fixturePost;function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML;}function attr(v){return esc(v).replaceAll('"','&quot;');}function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id==='view-'+name));document.dispatchEvent(new CustomEvent('pz-view-changed'));}`);
w.eval(fs.readFileSync('static/company-ui.js','utf8'));
const settle=()=>new Promise(r=>setTimeout(r,10));
(async()=>{clock();await settle();w.eval("showView('tracking')");await settle();assert.match(w.document.querySelector('#view-tracking').textContent,/Stundenkonto 2:00/);assert.ok(w.document.querySelector('#view-projects #project-select'));assert.ok(!w.document.querySelector('#view-tracking #project-select'));assert.ok(w.document.querySelector('[data-tracking-user]'));assert.ok(w.document.querySelector('[data-tracking-tab=account]'));const staff=w.document.querySelector('[data-tracking-user]');staff.value='2';staff.dispatchEvent(new w.Event('change'));await settle();assert.equal(calls.at(-1).body.user_id,'2');assert.ok(!w.document.querySelector('#view-tracking [data-leave]'));const back=w.document.querySelector('[data-tracking-user]');back.value='';back.dispatchEvent(new w.Event('change'));await settle();
w.document.querySelector('[data-day]').click();assert.match(w.document.querySelector('dialog.company-dialog').textContent,/Kassenupdate/);w.document.querySelector('dialog.company-dialog').close();
w.document.querySelector('[data-leave]').click();const form=w.document.querySelector('dialog.company-dialog form');form.dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true}));form.dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true}));await settle();assert.equal(calls.filter(x=>x.path.endsWith('/absence/submit')).length,1);assert.equal(form.querySelector('[type=submit]').disabled,true);
form.closest('dialog').close();w.eval("showView('calendar')");await settle();assert.ok(w.document.querySelector('[data-duty]'));assert.ok(w.document.querySelector('[data-type=holiday]'));page.window.close();console.log('Company UI: project separation, day details, calendar and duplicate-submit guard passed');})().catch(e=>{console.error(e);process.exitCode=1;page.window.close();});
