// Real runtime + local DOM regression. No external provider or production account.
const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pz-interface-'));
const server=spawn('python',['-u','-c',`import runtime,json
app=runtime.initialize()
import zammad_cache_runtime as zc
with app.db() as c:
 uid=c.execute('SELECT id FROM users').fetchone()['id']
 c.execute("INSERT INTO integrations(owner_id,provider,domain,username,secret,updated_at) VALUES(?,'zammad','https://example.invalid','uitest@example.invalid','fixture','')",(uid,))
 c.execute("INSERT OR REPLACE INTO provider_system_config(provider,domain,updated_at) VALUES('zammad','https://example.invalid','')")
 c.execute("INSERT INTO provider_access_state(owner_id,provider,state,message,checked_at) VALUES(?,'zammad','valid','','2026-09-14')",(uid,))
 for i,state in enumerate(['open','closed','pending reminder'],1):
  zc._upsert(c,uid,{'id':i,'number':str(i),'title':'Ticket '+str(i),'owner':{'email':'uitest@example.invalid'},'customer':{'email':'ticket'+str(i)+'@example.invalid'},'state':state,'updated_at':'2026-09-10T08:00:00Z'},'fixture')
 zc._upsert(c,uid,{'id':4,'number':'4','title':'Ticket ohne Besitzer','owner':None,'customer':{'email':'unassigned@example.invalid'},'state':'open','updated_at':'2026-09-10T09:00:00Z'},'fixture')
 zc._upsert(c,uid,{'id':5,'number':'5','title':'Ticket eines anderen Besitzers','owner':{'email':'other@example.invalid'},'customer':{'email':'other-customer@example.invalid'},'state':'open','updated_at':'2026-09-10T10:00:00Z'},'fixture')
 import customer_data
 customer_data.cache_rows(c,uid,'zammad',zc.cached_list(c,uid))
server=app.ThreadingHTTPServer(('127.0.0.1',0),app.App)
print(json.dumps({'port':server.server_port}),flush=True)
server.serve_forever()`],{env:{...process.env,DATA_DIR:dir,DB_BACKEND:'sqlite',DEMO_MODE:'1',SEED_DEMO:'0',ADMIN_USER:'uitest',ADMIN_PASSWORD:'interface-test-password'}});
let stderr='',page,done=false;server.stderr.on('data',b=>stderr+=b);
const watchdog=setTimeout(()=>{console.error('Interface runtime timed out',stderr.slice(-2500));process.exitCode=1;cleanup();},30000);
function cleanup(){done=true;clearTimeout(watchdog);if(page){page.window.setTimeout(()=>page.window.close(),300);}server.kill();fs.rmSync(dir,{recursive:true,force:true});}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(check,label){for(let i=0;i<160;i++){if(check())return;await sleep(50);}console.error('Browser errors:', page?.window.__testErrors, 'providers:', [...(page?.window.pzProviderStates||[])], 'list:', page?.window.document.querySelector('#view-zammad .list-status')?.textContent, 'mobile summaries:',page?.window.document.querySelectorAll('#view-zammad .pz-mobile-summary').length,'first row:',page?.window.document.querySelector('#view-zammad tbody tr')?.innerHTML?.slice(0,900),'dialog:',page?.window.document.querySelector('[data-provider-connect-message]')?.textContent);throw new Error('Timed out: '+label+' '+page?.window.document.querySelector('dialog.ui-dialog [role=alert]')?.textContent);}
(async()=>{const port=await new Promise((resolve,reject)=>{let text='';server.stdout.on('data',b=>{text+=b;for(const line of text.split('\n'))try{const x=JSON.parse(line);if(x.port)resolve(x.port);}catch{}});server.on('exit',()=>{if(!done)reject(new Error(stderr));});});const base='http://127.0.0.1:'+port;
const routed=await fetch(base+'/kalender');assert.equal(routed.status,200);assert.match(await routed.text(),/pz-frontend-version/,'SPA paths serve the application entry point');
const login=await fetch(base+'/api/v1/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'uitest',password:'interface-test-password'})});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];const calls=[],errors=[];
const me=await fetch(base+'/api/v1/me',{headers:{Cookie:cookie}}).then(r=>r.json());
const api=async(route,body={})=>{const r=await fetch(base+route,{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:JSON.stringify(body)});const data=await r.json();assert.equal(r.ok,true,route+': '+JSON.stringify(data));return data;};
const customer=await api('/api/v1/customers/profile',{name:'DOM Kunde',email:'test@example.invalid',phones:[]});
const contact=await api('/api/v1/customers/contact',{customer_id:customer.customer_id,name:'Kontakt Alpha',phones:[{number:'+49400123456',label:'Mobil'}]});
const otherCustomer=await api('/api/v1/customers/profile',{name:'DOM Kunde Zwei',phones:[]});
await api('/api/v1/customers/contact',{customer_id:otherCustomer.customer_id,name:'Kontakt Beta',phones:[{number:'+49400654321',label:'Mobil'}]});
const project=await api('/api/v1/projects',{name:'DOM Projekt',customer_id:customer.customer_id});
await api('/api/v1/provider/assign/customer',{provider:'zammad',external_key:'zammad:id:2',customer_id:customer.customer_id});const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!/Could not load|Not implemented: navigation/.test(e.message))errors.push(e.message);});
page=await JSDOM.fromURL(base,{resources:'usable',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.__testErrors=errors;w.fetch=async(url,opts={})=>{calls.push({url:String(url),body:opts.body});if(String(url).endsWith('/company/context'))await sleep(250);const r=await fetch(new URL(url,base),{...opts,headers:{...Object.fromEntries(new Headers(opts.headers)),Cookie:cookie}});if(!r.ok)console.error(String(url),r.status,await r.clone().text());return r;};w.Headers=Headers;w.Response=Response;w.Request=Request;w.AbortController=AbortController;w.confirm=w.prompt=w.alert=()=>{throw new Error('Native browser dialog is forbidden');};w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};w.addEventListener('error',e=>errors.push(e.error?.stack||e.message));w.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));}});
const w=page.window,q=s=>w.document.querySelector(s);
await until(()=>w.pzAdmin&&q('[data-dashboard-edit]'),'initial page');await w.refresh();await until(()=>q('.timeline-hours span').style.left,'timeline axis initialized');assert.ok(q('[data-release-info]'));await until(()=>q('[data-company-nav=calendar]'),'calendar independent readiness');
const originalWidth=w.innerWidth;Object.defineProperty(w,'innerWidth',{value:390,configurable:true});const swipe=(type,target,x,y=80)=>{const event=new w.Event(type,{bubbles:true,cancelable:true}),point={clientX:x,clientY:y};Object.defineProperty(event,'touches',{value:type==='touchend'?[]:[point]});Object.defineProperty(event,'changedTouches',{value:[point]});target.dispatchEvent(event);};q('.sidebar').classList.remove('open');swipe('touchstart',q('.timeline-scroll'),90);swipe('touchend',q('.timeline-scroll'),200);assert.equal(q('.sidebar').classList.contains('open'),false,'timeline swipe must not open the menu');swipe('touchstart',w.document.body,8);swipe('touchend',w.document.body,100);assert.equal(q('.sidebar').classList.contains('open'),true,'edge swipe still opens the menu');q('.sidebar-scrim').click();Object.defineProperty(w,'innerWidth',{value:originalWidth,configurable:true});
w.pzOpenNavTarget('settings-connections','Verbindungen');await until(()=>q('#integration-cards .integration-card'),'local connections');await sleep(300);let mutations=0;const archiveRequests=calls.filter(x=>x.url==='/api/v1/archive/status').length;const observer=new w.MutationObserver(records=>mutations+=records.length);observer.observe(q('#integration-cards'),{childList:true,subtree:true});await sleep(300);observer.disconnect();assert.equal(calls.filter(x=>x.url==='/api/v1/archive/status').length,archiveRequests,'DOM decoration must not trigger archive API requests');assert.ok(mutations<12,'Connection decoration must settle instead of triggering itself: '+mutations);
await w.pzAdmin.open('users');await until(()=>q('[data-user-id]'),'users initial load');assert.equal(q('[data-user-editor]'),null,'details appear only after selecting a user');q('[data-user-id]').click();await until(()=>q('.admin-user-dialog[open]'),'user detail dialog');assert.ok(q('[data-add-user]'));assert.equal(w.document.querySelectorAll('.role-card').length,1);
q('[data-user-tab=work]').click();await until(()=>q('[data-user-pane=work]').textContent.includes('Urlaub'),'employee work tab');q('.admin-user-dialog [data-close]').click();
await w.pzAdmin.open('api');await until(()=>q('[data-admin-pane=api] [data-api-create]'),'API pane');assert.equal(q('[data-admin-pane=api]').classList.contains('hidden'),false);
assert.equal(q('[data-admin-pane=super]'),null);assert.equal(q('[data-admin-tab=super]'),null);
await w.pzAdmin.open('roles');assert.equal(w.document.querySelectorAll('.role-card').length,1);assert.ok(q('[data-add-role]'));
await w.pzAdmin.open('users');q('[data-add-user]').click();const form=q('dialog.ui-dialog form');form.elements.username.value='NeuerTechniker';form.elements.password.value='new-interface-password';assert.ok(form.elements.must_change_password,'new users can receive a temporary password');assert.doesNotMatch(form.textContent,/Authenticator einrichten/);form.elements.must_change_password.checked=false;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>q('[data-user-list]').textContent.includes('NeuerTechniker'),'user persisted');await until(()=>q('.admin-user-dialog [data-user-title]')?.textContent==='NeuerTechniker','created user detail');
const roleSearch=q('.role-picker input');roleSearch.focus();roleSearch.value='Benutzer';roleSearch.dispatchEvent(new w.Event('input',{bubbles:true}));assert.ok(q('.role-chip'));q('.admin-user-dialog [data-close]').click();const search=q('[data-user-search]');search.value='NeuerTech';search.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.document.querySelectorAll('[data-user-list] [data-user-id]').length,1);search.value='';search.dispatchEvent(new w.Event('input',{bubbles:true}));
const temporary=await api('/api/v1/admin/user/create',{username:'TemporärerBenutzer',password:'temporary-interface-password',must_change_password:true});assert.ok(temporary.id);const temporaryLogin=await fetch(base+'/api/v1/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'TemporärerBenutzer',password:'temporary-interface-password'})});assert.equal(temporaryLogin.status,200);const temporaryCookie=temporaryLogin.headers.get('set-cookie').split(';')[0],temporaryMe=await fetch(base+'/api/v1/me',{headers:{Cookie:temporaryCookie}}).then(r=>r.json());assert.equal(temporaryMe.user.password_change_required,true);const temporaryBlocked=await fetch(base+'/api/v1/customers/data',{method:'POST',headers:{Cookie:temporaryCookie,'Content-Type':'application/json','X-CSRF-Token':temporaryMe.csrf},body:'{}'});assert.equal(temporaryBlocked.status,403);assert.equal((await temporaryBlocked.json()).password_change_required,true);const temporaryChanged=await fetch(base+'/api/v1/account/password',{method:'POST',headers:{Cookie:temporaryCookie,'Content-Type':'application/json','X-CSRF-Token':temporaryMe.csrf},body:JSON.stringify({current_password:'temporary-interface-password',password:'permanent-interface-password',confirmation:'permanent-interface-password'})});assert.equal(temporaryChanged.status,200);assert.equal((await fetch(base+'/api/v1/me',{headers:{Cookie:temporaryCookie}}).then(r=>r.json())).user.password_change_required,false);
q('[data-dashboard-edit]').click();const height=q('[data-widget-height=stats]');height.value='600';height.dispatchEvent(new w.Event('input',{bubbles:true}));q('[data-widget-editor-save]').click();await until(()=>q('[data-dashboard-widget=stats]').style.getPropertyValue('--widget-height')==='600px','widget size saved');assert.equal(q('.dashboard-grid').children.length,4);
for(let i=0;i<3;i++){w.pzOpenNavTarget('settings-api','API');await sleep(100);w.pzOpenNavTarget('settings-profile','Profil');await sleep(100);}assert.equal(w.document.querySelectorAll('[data-user-api-settings]').length,1,'API settings remain unique across navigation');assert.ok(q('#view-settings-api [data-user-api-settings]'));assert.equal(q('[data-company-nav=staff-settings]'),null,'redundant staff settings navigation is removed');assert.equal(q('.admin-nav-submenu [data-admin-open]')?.dataset.adminOpen,'company','company master data is the first Admin item');
q('.nav[data-view=customers]').click();await until(()=>q('.customer-card-button[data-customer-id]'),'customer overview');await sleep(800);const alpha=q('.customer-card-button[data-customer-id="'+customer.customer_id+'"]'),beta=q('.customer-card-button[data-customer-id="'+otherCustomer.customer_id+'"]');assert.match(alpha.textContent,/Kontakt Alpha/);assert.doesNotMatch(alpha.textContent,/Kontakt Beta/);assert.match(beta.textContent,/Kontakt Beta/);assert.doesNotMatch(beta.textContent,/Kontakt Alpha/);assert.equal(q('.customer-card-button button'),null,'no nested interactive buttons');
const detailBefore=calls.filter(x=>x.url==='/api/v1/customers/detail').length;await w.openCustomer(customer.customer_id);assert.equal(calls.filter(x=>x.url==='/api/v1/customers/detail').length-detailBefore,1,'one shared customer detail request');assert.equal(q('.customer-detail-grid'),null);assert.ok(q('[data-pane=master] [data-new-contact]'));q('[data-master-edit]').click();q('[data-master-form] [name=city]').value='Neue Stadt';q('[data-master-form]').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>q('[data-customer-quick]')?.textContent.includes('Neue Stadt'),'saved customer header refreshed');assert.ok(q('[data-pane=master] [data-new-contact]'),'contact creation survives saving');q('[data-master-edit]').click();q('[data-master-cancel]').click();await sleep(100);assert.ok(q('[data-pane=master] [data-new-contact]'),'contact creation survives cancel');await until(()=>q('.customer-detail-dialog [data-tab=projects]'),'customer projects tab');q('.customer-detail-dialog [data-tab=projects]').click();await until(()=>q('.customer-detail-dialog').textContent.includes('DOM Projekt'),'linked active project');assert.ok(q('[data-customer-project-new]'));await until(()=>q('[data-customer-audit-block]')?.textContent.includes('master_updated')||q('[data-customer-audit-block]')?.textContent.includes('Stammdaten'),'customer audit block survives edits');
q('.customer-detail-dialog').close();w.showView('projects');await sleep(300);assert.equal(q('#customer-form'),null);assert.equal(q('#category-form'),null);assert.equal(q('#project-activity'),null);
await w.pzCompany.assignProvider('teamviewer',{external_key:'fixture-only'});assert.ok(q('dialog.company-dialog [name=customer_id] option[value="'+otherCustomer.customer_id+'"]'));q('dialog.company-dialog [data-close]').click();await w.eval("post('/api/v1/customers/delete',{customer_id:"+otherCustomer.customer_id+"})");await w.pzCompany.assignProvider('teamviewer',{external_key:'fixture-only'});assert.equal(q('dialog.company-dialog [name=customer_id] option[value="'+otherCustomer.customer_id+'"]'),null,'deleted customer removed from assignment without reload');assert.ok(q('dialog.company-dialog [name=project_id] option[value="'+project.id+'"]'));q('dialog.company-dialog [data-close]').click();
q('.nav[data-view=zammad]').click();await until(()=>q('#view-zammad tbody').children.length===4,'cached ticket rows');await sleep(400);
assert.equal(q('#view-zammad [data-range]'),null);const ticketRows=[...w.document.querySelectorAll('#view-zammad tbody tr')];assert.equal(ticketRows.some(r=>r._pzRow.ticket_id==='4'),false,'Zammad master sync removes unowned tickets');assert.equal(ticketRows.find(r=>r._pzRow.ticket_id==='2').dataset.pzAssigned,'blue');for(const row of ticketRows){assert.equal(row.querySelectorAll('[data-pz-assign-button]').length,1);assert.equal(row.querySelectorAll(':scope > td:not(.pz-mobile-summary) .pz-assignment-dot').length,1,'one desktop color dot');assert.equal(row.querySelectorAll('.pz-mobile-summary .mobile-assignment-dot').length,1,'one mobile color dot');assert.equal(row.querySelectorAll('.pz-mobile-summary .pz-assignment-dot').length,0,'no duplicated desktop dot in mobile summary');}const requestCount=calls.filter(x=>x.url.includes('/integrations/list')).length;
q('#view-zammad [data-filter=open]').click();await sleep(100);assert.equal(ticketRows.filter(r=>!r.hidden).length,1,'Eigene Tickets excludes unknown owners');assert.match(q('#view-zammad .list-status').textContent,/1 von 4/);assert.equal(calls.filter(x=>x.url.includes('/integrations/list')).length,requestCount);
const ownerHeader=q('#view-zammad th[data-column-key=owner_display]');assert.ok(ownerHeader);assert.equal(q('#view-zammad [data-zammad-employee]').value,'own');
const columnsButton=q('#view-zammad thead tr:first-child th:last-child .table-column-edit');assert.ok(columnsButton,'column editor is a pencil in the final header');assert.equal([...w.document.querySelectorAll('#view-zammad button')].some(b=>b.textContent.trim()==='Spalten'),false);columnsButton.click();const editor=q('.table-column-dialog'),column=[...editor.querySelectorAll('.table-column-editor-row')].find(r=>r.textContent.includes('Besitzer'));await until(()=>[...w.document.querySelectorAll('#view-zammad .mobile-ticket-owner')].some(el=>el.textContent.includes('uitest')),'mobile ticket owner');assert.equal(editor.querySelector('input[type=number]'),null,'width is changed only at the table header');const visibility=column.querySelector('input[type=checkbox]');visibility.checked=false;visibility.dispatchEvent(new w.Event('change'));assert.equal(q('#view-zammad th[data-column-key=owner_display]'),null);visibility.checked=true;visibility.dispatchEvent(new w.Event('change'));assert.ok(q('#view-zammad th[data-column-key=owner_display]'));const resize=q('#view-zammad th[data-column-key=owner_display] .table-column-resize');resize.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.match(w.localStorage.getItem('pz-table-v1:'+me.user.id+':zammad'),/owner_display/);editor.querySelector('[data-reset]').click();assert.ok(q('#view-zammad th[data-column-key=owner_display]'));editor.querySelector('[data-close]').click();assert.equal(calls.filter(x=>x.url.includes('/integrations/list')).length,requestCount,'column changes do not fetch provider data');

q('#view-zammad [data-filter=all]').click();q('#view-zammad input[type=search]').value='Ticket 2';q('#view-zammad input[type=search]').dispatchEvent(new w.Event('input',{bubbles:true}));await sleep(150);assert.equal(q('#view-zammad tbody tr')._pzRow.raw.title,'Ticket 2');
q('.nav[data-view=starface]').click();await until(()=>q('.provider-connect-dialog').open,'STARFACE blocking dialog');assert.match(q('[data-provider-connect-message]').textContent,/Client Secret/);assert.equal(q('[data-provider-connect-yes]').hidden,true);q('[data-provider-connect-no]').click();q('.nav[data-view=teamviewer]').click();await until(()=>q('.provider-connect-dialog').open,'TeamViewer blocking dialog');assert.match(q('[data-provider-connect-message]').textContent,/TeamViewer/);assert.equal(q('#view-teamviewer').classList.contains('active-view'),false);q('[data-provider-connect-no]').click();
const newUser=(await api('/api/v1/admin/context')).users.find(u=>u.username==='NeuerTechniker');const loginUser=await fetch(base+'/api/v1/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'NeuerTechniker',password:'new-interface-password'})});const staffCookie=loginUser.headers.get('set-cookie').split(';')[0];await api('/api/v1/admin/user/active',{user_id:newUser.id,active:false});assert.equal((await fetch(base+'/api/v1/me',{headers:{Cookie:staffCookie}})).status,401);const denied=await fetch(base+'/api/v1/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'NeuerTechniker',password:'new-interface-password'})});assert.equal(denied.status,401);await api('/api/v1/admin/user/active',{user_id:newUser.id,active:true});await api('/api/v1/admin/user/mfa-reset',{user_id:newUser.id});const history=await api('/api/v1/history/object',{entity_type:'user',entity_id:newUser.id});assert.equal(history.history.find(e=>e.action==='mfa_reset').actor_id,me.user.id);
// Full 0.7.3 workflows use the actual runtime and DOM, including route permissions.
await api('/api/v1/company/model/save',{user_id:newUser.id,valid_from:'2026-01-01',mode:'weekly',hours:40,weekdays:[0,1,2,3,4],subdivision:'SH'});
const staffLogin=await fetch(base+'/api/v1/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'NeuerTechniker',password:'new-interface-password'})});const staffCookie2=staffLogin.headers.get('set-cookie').split(';')[0];
const staffMe=await fetch(base+'/api/v1/me',{headers:{Cookie:staffCookie2}}).then(r=>r.json());
// Customer permissions apply to shared records and the HTTP response fields.
const staffApi=async(route,body={})=>{const response=await fetch(base+route,{method:'POST',headers:{Cookie:staffCookie2,'Content-Type':'application/json','X-CSRF-Token':staffMe.csrf},body:JSON.stringify(body)});return {status:response.status,data:await response.json()};};
const ordinary=(await api('/api/v1/admin/context')).roles.find(r=>r.key==='user');
const limited=await api('/api/v1/admin/role/save',{name:'Lesen für Kundentest',permissions:['customers.view_basic','api.tokens.manage_own']});await api('/api/v1/admin/user/roles',{user_id:newUser.id,role_ids:[limited.role_id]});
const shared=await staffApi('/api/v1/customers/data');assert.equal(shared.status,200);assert.ok(shared.data.customers.some(c=>c.id===customer.customer_id));assert.equal(shared.data.customers.find(c=>c.id===customer.customer_id).contacts,undefined);
const issued=await staffApi('/api/v1/api/tokens/create',{name:'Kundenprüfung',permissions:['customers.read']});assert.equal(issued.status,201,JSON.stringify(issued.data));const external=await fetch(base+'/api/v1/external/customers/'+customer.customer_id,{headers:{Authorization:'Bearer '+issued.data.token}}).then(r=>r.json());assert.equal(external.customer.name,'DOM Kunde');assert.equal(external.customer.contacts,undefined,'API respects contact permission');assert.equal(external.customer.email,undefined);
assert.equal((await staffApi('/api/v1/customers/contact/update',{id:contact.contact_id,name:'Verboten'})).status,403);assert.equal((await staffApi('/api/v1/audit/history',{entity_type:'customer',entity_id:customer.customer_id})).status,403);
await api('/api/v1/admin/user/roles',{user_id:newUser.id,role_ids:[ordinary.id]});assert.equal((await staffApi('/api/v1/customers/contact/update',{id:contact.contact_id,name:'Kontakt Alpha aktualisiert',email:'contact@example.invalid'})).status,200);
const customerHistory=await api('/api/v1/history/object',{entity_type:'customer',entity_id:customer.customer_id});assert.ok(customerHistory.history.some(e=>e.actor==='NeuerTechniker'&&e.action==='contact_updated'));await api('/api/v1/admin/role/delete',{id:limited.role_id});
await w.pzAdmin.open('company');await until(()=>q('[data-admin-pane=company] [name=subdivision]'),'company master form');const companyForm=q('[data-admin-pane=company] form');companyForm.elements.name.value='Testfirma';companyForm.elements.subdivision.value='HH';companyForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>q('[data-company-master-status]').textContent.includes('gespeichert'),'company master saved');assert.equal((await api('/api/v1/work-models/admin')).default_subdivision,'HH');
w.pzOpenNavTarget('settings-data','Import & Export');await sleep(200);assert.ok(q('#view-settings-data #csv-import-button'));assert.ok(q('#view-settings-data #csv-export-button'));assert.equal(w.document.querySelectorAll('[data-import-export]').length,1);
w.pzOpenNavTarget('settings-profile','Profil');await until(()=>q('.pz-session-history'),'session history');assert.equal(q('.pz-session-history').open,false);q('.pz-session-history').open=true;q('[data-pz-sessions-refresh]').click();await sleep(100);assert.equal(q('.pz-session-history').open,true);
const toastItem=w.pzToast('Schließtest','info',60000);toastItem.querySelector('.pz-toast-dismiss').click();assert.equal(toastItem.isConnected,false);
const absence=await fetch(base+'/api/v1/company/absence/submit',{method:'POST',headers:{Cookie:staffCookie2,'Content-Type':'application/json','X-CSRF-Token':staffMe.csrf},body:JSON.stringify({kind:'unpaid',whole_day:true,from:'2026-09-21',to:'2026-09-21',note:'UI Termin'})}).then(r=>r.json());assert.ok(absence.id,JSON.stringify(absence));
await until(()=>q('#notification-bell'),'notification center readiness');q('#notification-bell').click();await until(()=>q('[data-inbox-list]')?.textContent.includes('Abwesenheitsantrag prüfen'),'action appears in notification center');assert.equal(q('.work-panel').hidden,true,'work controls stay hidden in inbox');
q('[data-inbox-list] button').click();await until(()=>q('dialog.company-dialog[open]')?.textContent.includes('UI Termin'),'exact request opens');q('dialog.company-dialog[open]').close();
q('[data-inbox-mode=all]').click();await until(()=>q('[data-inbox-list]')?.textContent.includes('Als gelesen markieren'),'personal messages');[...w.document.querySelectorAll('[data-inbox-list] button')].find(b=>b.textContent==='Als gelesen markieren').click();await sleep(120);assert.match(q('#notification-bell').title,/1 zu bestätigen/,'reading does not approve');
w.showView('tracking');await until(()=>q('[data-tracking-date]'),'tracking page');q('[data-tracking-date]').value='2026-09-07';q('[data-tracking-date]').dispatchEvent(new w.Event('change'));await until(()=>q('[data-day="2026-09-07"]'),'requested work week');q('[data-day="2026-09-07"]').click();await until(()=>q('.time-history'),'time detail history');[...q('dialog.company-dialog').querySelectorAll('button')].find(b=>b.textContent==='Arbeitszeit / Pausen bearbeiten').click();
const correction=q('dialog.company-dialog form');assert.equal(correction.elements.start.value.slice(0,10),'2026-09-07');assert.equal(correction.elements.end.value.slice(0,10),'2026-09-07');correction.elements.start.value='2026-09-07T08:00';correction.elements.end.value='2026-09-07T17:00';correction.elements.note.value='UI Nachtrag';q('[data-pause-add]').click();q('[data-pause-row] [data-start]').value='2026-09-07T12:00';q('[data-pause-row] [data-end]').value='2026-09-07T12:30';
correction.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));correction.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>correction.dataset.saved==='1','manual time saved directly');assert.equal(calls.filter(c=>c.url.endsWith('/correction/submit')).length,1);q('dialog.company-dialog').close();await until(()=>q('[data-day="2026-09-07"]'),'tracking after save');assert.doesNotMatch(q('[data-requests]').textContent,/Genehmigt|correction/,'direct corrections are not approval requests');q('[data-day="2026-09-07"]').click();await until(()=>q('.time-history').textContent.includes('Arbeitszeit nachgestempelt'),'audited correction in detail');assert.match(q('.time-history').textContent,/Netto: – → 8:30/);q('dialog.company-dialog').close();
w.showView('calendar');await until(()=>q('.company-calendar-cell'),'calendar grid');assert.equal(w.document.querySelectorAll('.company-calendar-weekdays span').length,7);assert.equal(w.document.querySelectorAll('.company-calendar-cell').length%7,0,'complete weeks including adjacent month');assert.ok(q('.company-calendar-cell.other-month'));const mobileCalendar=q('.company-calendar-mobile');assert.ok(mobileCalendar);assert.ok(mobileCalendar.querySelectorAll(':scope > .company-calendar-day').length>=28,'mobile month is a complete agenda');assert.ok(q('[data-company-nav=calendar]').classList.contains('active'),'calendar navigation remains selected');const mobileWork=mobileCalendar.querySelector('.company-calendar-event.work');assert.ok(mobileWork,'mobile agenda includes work entries');mobileWork.click();await until(()=>q('dialog.company-time-detail[open]'),'shared mobile work detail');q('dialog.company-time-detail[open]').close();
w.showView('bookkeeping');await sleep(200);const book=q('[data-pz-nav-group=bookkeeping]');assert.ok(book);assert.ok(book.querySelector('[data-company-nav=employee-billing]'),'employee accounts in bookkeeping');assert.ok(book.querySelector('[data-company-nav=absence-approvals]'),'absence administration is grouped in bookkeeping');q('[data-pz-nav-group=bookkeeping] .pz-nav-toggle').click();await sleep(200);assert.equal(q('[data-pz-nav-group=bookkeeping] .pz-nav-submenu').hidden,true,'bookkeeping stays collapsed after user choice');await w.pzAdmin.open('policies');assert.ok(q('[data-staff-policy-form]'),'worktime policies moved into central policies');assert.ok(q('[data-day-kind-form]'),'custom day types moved into central policies');const helpLabel=q('[data-admin-pane=policies] [name=password_min_length]').closest('label'),helpButton=helpLabel.querySelector('.field-help-button');assert.ok(helpButton.closest('.field-label-line'),'help question mark sits directly next to its label');helpButton.click();await until(()=>q('dialog.ui-dialog[open]')?.textContent.includes('mindestens 12 Zeichen'),'policy help opens only after clicking the question mark');q('dialog.ui-dialog[open]').close();
await w.pzAdmin.open('integrations');await until(()=>w.document.querySelectorAll('[data-admin-pane=integrations] [data-integration-sync]').length===3,'company synchronization policies assigned to each integration');assert.equal(q('[data-admin-pane=integrations] [data-company-sync]'),null,'shared synchronization block removed');
await w.pzAdmin.open('notifications');assert.match(q('[data-admin-pane=notifications]').textContent,/Sicherheitsmails.*Richtlinien/);
await w.pzProjects.open(null,project.id);await until(()=>q('[data-detail-status]'),'project detail');assert.equal(q('[data-detail-status]').value,'open');q('[data-detail-status]').value='closed';q('[data-detail-save]').click();await until(()=>q('[data-detail-status]')?.value==='closed'&&q('[data-detail-billing]'),'closed project offers billing');
q('.nav[data-view=logs]').click();await until(()=>q('[data-log-limit]'),'log table');assert.deepEqual([...q('[data-log-limit]').options].map(option=>option.value),['25','50','100','150','all']);assert.ok(q('.logs-panel .log-table-wrap'));assert.equal(q('[data-log-limit]').value,'25');
// Mandatory enrollment is enforced through the complete runtime, including native login.
await api('/api/v1/admin/policies/save',{policies:{two_factor_mode:'required'}});
assert.equal((await fetch(base+'/api/v1/me',{headers:{Cookie:cookie}})).status,401);
const sign=body=>fetch(base+'/api/v1/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'NeuerTechniker',password:'new-interface-password',...body})});
const selectionResponse=await sign({}),selection=await selectionResponse.json();assert.equal(selection.method_selection,true);assert.equal(selection.enrollment_required,true);assert.equal(selectionResponse.headers.get('set-cookie'),null);const challengeResponse=await sign({mfa_method:'totp'}),challenge=await challengeResponse.json();assert.equal(challenge.enrollment_required,true);assert.equal(challenge.mfa_method,'totp');
const crypto=require('node:crypto'),alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const char of challenge.secret.replace(/=/g,''))bits+=alphabet.indexOf(char).toString(2).padStart(5,'0');const bytes=Buffer.from((bits.match(/.{8}/g)||[]).map(b=>parseInt(b,2))),counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const hash=crypto.createHmac('sha1',bytes).update(counter).digest(),offset=hash[19]&15,otp=String((hash.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');
const verified=await sign({mfa_method:'totp',otp}),verifiedBody=await verified.json();assert.equal(verifiedBody.ok,true);assert.equal(verifiedBody.recovery_codes.length,8);const verifiedCookie=verified.headers.get('set-cookie').split(';')[0];assert.equal((await fetch(base+'/api/v1/me',{headers:{Cookie:verifiedCookie}})).status,200);
const native=await fetch(base+'/api/v1/auth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'NeuerTechniker',password:'new-interface-password'})});assert.equal((await native.json()).mfa_required,true);
assert.equal((await sign({otp})).status,401,'OTP cannot be reused');
assert.deepEqual(errors,[],JSON.stringify(errors));console.log('Interface runtime: first admin load, roles, employee work settings, API, removed Systemschutz, user creation, dashboard heights, customer projects STARFACE guard, local ticket filters, inbox, direct time corrections with pauses/history, calendar, collapsible navigation, project detail and enforced web/native 2FA passed');
})().catch(e=>{console.error(e);console.error(stderr.slice(-1800));process.exitCode=1;}).finally(cleanup);
