const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<section id="view-tracking" class="view active-view"></section><div data-admin-pane="work-models"></div>',{url:'https://project.test',runScripts:'outside-only'}),w=dom.window;
let calls=[],resolveSave;const day={day:'2026-09-14',target_seconds:null,actual_seconds:25200,pause_seconds:3600,holiday_seconds:0,difference_seconds:null,remaining_seconds:null,closed:false};
const summary={target_seconds:null,actual_seconds:25200,holiday_seconds:0,closed_difference_seconds:null,missing_model_days:1};
const info={selected_day:'2026-09-14',today:'2026-09-14',as_of:'2026-09-14T12:00:00Z',day,week:summary,month:summary,week_start:'2026-09-14',week_end:'2026-09-20',models:[],days:[day],states:{SH:'Schleswig-Holstein'}};
w.post=async(path,body)=>{calls.push({path,body});if(path.endsWith('/overview'))return info;if(path.endsWith('/admin'))return {today:'2026-09-14',states:info.states,models:[],users:[{id:1,username:'<b>Techniker</b>',active:1}]};return new Promise(r=>resolveSave=r);};
w.eval(fs.readFileSync('static/work-models-ui.js','utf8'));const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
 await w.pzWorkModels.load();const host=w.document.querySelector('[data-work-overview]');assert.match(host.textContent,/kein Arbeitszeitmodell/);assert.equal(host.querySelector('dd').textContent,'–');assert.match(host.textContent,/7,00 h/);
 await w.pzWorkModels.admin();assert.equal(w.document.querySelector('b'),null);const select=w.document.querySelector('[data-wm-person]');select.value='1';select.dispatchEvent(new w.Event('change'));const form=w.document.querySelector('[data-wm-form]');assert.equal(form.querySelectorAll('[name=weekdays]:checked').length,5);
 form.querySelector('[name=subdivision]').value='SH';form.querySelector('[name=hours]').value='173';form.querySelector('[name=mode]').value='monthly';form.querySelector('[type=submit]').click();assert.equal(form.querySelector('[type=submit]').disabled,true);form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(calls.filter(c=>c.path.endsWith('/save')).length,1);assert.equal(calls.at(-1).body.hours,'173');assert.deepEqual([...calls.at(-1).body.weekdays],[0,1,2,3,4]);resolveSave({ok:true});await tick();assert.match(form.querySelector('[data-wm-success]').textContent,/Gespeichert/);assert.equal(form.querySelector('[type=submit]').disabled,true);
 await w.pzWorkModels.admin();const s=w.document.querySelector('[data-wm-person]');s.value='1';s.dispatchEvent(new w.Event('change'));const f=w.document.querySelector('[data-wm-form]');f.querySelector('[name=subdivision]').value='SH';w.post=async()=>{throw Error('Konflikt');};f.querySelector('[type=submit]').click();await tick();assert.match(f.querySelector('[data-wm-error]').textContent,/Konflikt/);assert.equal(f.querySelector('[name=hours]').value,'40');assert.equal(f.querySelector('[type=submit]').disabled,false);
 const before=calls.length;w.document.querySelector('#view-tracking').classList.remove('active-view');w.document.dispatchEvent(new w.CustomEvent('pz-data-changed',{detail:{path:'/api/v1/work/end'}}));await tick();assert.equal(calls.length,before);
 dom.window.close();console.log('Work models UI: unknown values, work totals, weekdays, save lock, errors and inactive views passed');
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
